DCT_SFAC = {
    'Aeric Chromic Vertic Epiaqualfs': 54,
    'Aeric Endoaqualfs': 88,
    'Aeric Fluvaquents': 79,
    'Aeric Vertic Epiaqualfs': 54,
    'Aquents': 50,
    'Aquertic Argiudolls': 83,
    'Aquertic Chromic Hapludalfs': 79,
    'Aquertic Hapludalfs': 79,
    'Aquertic Hapludolls': 92,
    'Aquertic Udifluvents': 84,
    'Aquic Argiudolls': 85,
    'Aquic Cumulic Hapludolls': 93,
    'Aquic Hapludolls': 100,
    'Aquic Pachic Argiudolls': 96,
    'Aquic Pachic Hapludolls': 98,
    'Aquic Udifluvents': 98,
    'Aquic Udipsamments': 60,
    'Aquic Udorthents': 84,
    'Aquollic Hapludalfs': 90,
    'Aquolls': 50,
    'Argiaquic Argialbolls': 80,
    'Chromic Vertic Albaqualfs': 74,
    'Cumulic Endoaquolls': 84,
    'Cumulic Hapludolls': 99,
    'Cumulic Vertic Endoaquolls': 79,
    'Cumulic Vertic Epiaquolls': 81,
    'Dystric Eutrudepts': 97,
    'Entic Hapludolls': 90,
    'Fluvaquentic Endoaquolls': 83,
    'Fluvaquentic Hapludolls': 85,
    'Fluvaquentic Vertic Endoaquolls': 93,
    'Fluvaquents': 50,
    'Fluventic Hapludolls': 85,
    'Glossic Hapludalfs': 86,
    'Lamellic Udipsamments': 67,
    'Limnic Haplosaprists': 72,
    'Lithic Endoaquolls': 45,
    'Lithic Hapludalfs': 42,
    'Lithic Hapludolls': 42,
    'Lithic Haplustolls': 48,
    'Mollic Endoaqualfs': 85,
    'Mollic Epiaqualfs': 80,
    'Mollic Fluvaquents': 83,
    'Mollic Hapludalfs': 95,
    'Mollic Oxyaquic Hapludalfs': 90,
    'Mollic Udifluvents': 88,
    'Oxyaquic Argiudolls': 100,
    'Oxyaquic Dystrudepts': 42,
    'Oxyaquic Eutrudepts': 42,
    'Oxyaquic Hapludalfs': 85,
    'Oxyaquic Hapludolls': 100,
    'Oxyaquic Haplustolls': 81,
    'Oxyaquic Udifluvents': 88,
    'Oxyaquic Vertic Argiudolls': 97,
    'Oxyaquic Vertic Hapludalfs': 79,
    'Pachic Argiudolls': 100,
    'Pachic Hapludolls': 100,
    'Pachic Haplustolls': 78,
    'Psammentic Hapludalfs': 67,
    'Terric Haplosaprists': 87,
    'Thapto-Histic Fluvaquents': 85,
    'Typic Albaqualfs': 87,
    'Typic Argialbolls': 77,
    'Typic Argiaquolls': 82,
    'Typic Argiudolls': 100,
    'Typic Calciaquolls': 78,
    'Typic Calciudolls': 84,
    'Typic Endoaqualfs': 66,
    'Typic Endoaquerts': 70,
    'Typic Endoaquolls': 94,
    'Typic Eutrudepts': 78,
    'Typic Fluvaquents': 80,
    'Typic Haplohemists': 64,
    'Typic Haplosaprists': 64,
    'Typic Hapludalfs': 89,
    'Typic Hapludolls': 100,
    'Typic Natraquerts': 52,
    'Typic Paleudalfs': 86,
    'Typic Quartzipsamments': 58,
    'Typic Udifluvents': 95,
    'Typic Udipsamments': 58,
    'Typic Udorthents': 72,
    'Udertic Haplustolls': 80,
    'Udic Haplustolls': 80,
    'Udic Ustorthents': 74,
    'Udifluvents': 50,
    'Udollic Endoaqualfs': 90,
    'Vertic Albaqualfs': 80,
    'Vertic Argialbolls': 80,
    'Vertic Argiaquolls': 90,
    'Vertic Endoaquepts': 78,
    'Vertic Endoaquolls': 75,
    'Vertic Epiaqualfs': 81,
    'Vertic Epiaquolls': 79,
    'Vertic Fluvaquents': 67,
}

DCT_MFAC = {
    'coprogenous': 0,
    'fine-silty': 0,
    'fine-silty over clayey': 0,
    'organic': 0,
    'clayey': 4,
    'clayey over loamy': 4,
    'fine': 4,
    'fine-loamy': 4,
    'fine-loamy over clayey': 4,
    'very-fine': 4,
    'fine-loamy over sandy': 4,
    'coarse-loamy': 12,
    'coarse-loamy over clayey': 12,
    'coarse-silty': 12,
    'coarse-silty over clayey': 12,
    'loamy': 12,
    'mesic': 35,
    'mixed': 35,
    'sandy': 35,
    'sandy over clayey': 35,
    'sandy over loamy': 35,
    'sandy-skeletal': 35,
    # all other classes containing *skeletal: 12,
    # all other set to 5
}

DCT_EJ_SUBST = {
    'Adair': 10,
    'Armstrong': 10,
    'Ashgrove': 10,
    'Bucknell': 10,
    'Cerlin': 15,
    'Clarinda': 15,
    'Clearfield': 20,
    'Donnan': 20,
    'Galland': 15,
    'Keswick': 10,
    'Lagonda': 5,
    'Lamoni': 10,
    'Lineville': 20,
    'Malvern': 20,
    'Mystic': 15,
    'Northboro': 15,
    'Rinda': 15,

    # dense till deductions
    'Cresco': 5,
    'Cresken': 5,
    'Protivin': 5,
    'Jameston': 5,
    'Lourdes': 5,
    'Riceville': 5,

    # sandy deductions
    'Farrar': 15,
    'Olin': 10,

    # clayey loess deductions
    'Appanoose': 15,
    'Kniffin': 15,
    'Seymour': 10,
    'Rathbun': 15,

    # old caly loamDeductions
    'Shelby': 5,
    'Gara': 5,
    'Lindley': 5,
}

DCT_EJ_ADD = {
    'Macksburg': 15,
    'Mahaska': 15,
    'Kalona': 10,
    'Rowley': 10,
    'Waukee': 10
    # All components in map units 221B	10
}

